/* @kalzit.for ui_check
Makes a checkbox (as generated by uiCheckbox) appear checked.
This happens *without* triggering any connected listeners.

Usage example:
```
$box = {print: "This will not happen in this example"} uiCheckbox "".
uiCheck: box.
```
*/
this.uiCheck = function(checkbox){
	//The Checkbox from the standard library is inside a div, so we need to get the "real" checkbox (firstChild)
	checkbox.firstChild.checked = true;
}