#!/bin/sh
folder="$(dirname $0)"
cd "$folder/../../.."

#Test if run from a writable folder - if not, go to desktop
touch ./writingTest.txt
if [ ! -f ./writingTest.txt ]
then
	cd ~/Applications
	open ./
else
	rm ./writingTest.txt
fi

curl https://raw.githubusercontent.com/triploit/Kalzit/master/utilities/installer/main.sh | sh